#!/usr/bin/env python2.7

from __future__ import print_function

import keyboard, LED, random

led = LED.LED()

def basic():
    return random.randint(0, 255)

def filterer(rand, ratio):
    def func():
        return rand() if random.random() < ratio else 0
    return func

def expo():
    return random.expovariate(1 / 127.0)

HANDLER = {
    'q': led.exit,
    '+': lambda: led.scroller.change_speed(-10),
    '=': lambda: led.scroller.change_speed(-10),
    '-': lambda: led.scroller.change_speed(10),
    '_': lambda: led.scroller.change_speed(10),
    ' ': led.scroller.pause,
    '/': led.scroller.reverse,
    'b': led.blackout,
    'c': led.clear,
    'r': lambda: led.randomize(basic),
    's': lambda: led.randomize(expo),
    't': lambda: led.randomize(filterer(expo, 0.50)),
    'u': lambda: led.randomize(filterer(basic, 0.50)),
    'v': lambda: led.randomize(filterer(expo, 0.20)),
    'w': lambda: led.randomize(filterer(basic, 0.20)),
    'x': lambda: led.randomize(filterer(expo, 0.08)),
    'y': lambda: led.randomize(filterer(basic, 0.12)),
    }

def handle_keystrokes(ch):
    HANDLER.get(ch, lambda: print('Don\'t understand character', ch, ord(ch)))()

thread = keyboard.threaded(handle_keystrokes)

try:
    led.run()
except KeyboardInterrupt:
    led.exit()
